"""
modules/security/base.py
─────────────────────────
Abstract Base Class that every Security Engine implementation must satisfy.

ZERO-COUPLING CONTRACT:
  This module imports ONLY from:
    • Python standard library
    • ``core.schemas``
  It MUST NOT import from:
    • ``modules.history``
    • ``modules.compression``
    • Any third-party LLM SDK

All concrete implementations (e.g. ``DefaultSecurityEngine``) depend on this
interface, enabling transparent swapping without pipeline refactoring.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Dict, Tuple

from core.schemas import SecurityReport


class BaseSecurityEngine(ABC):
    """
    Contract interface for the Security Engine layer.

    Responsibilities enforced via this ABC:
      1. **Input Inspection** — Detect prompt injection / jailbreak attempts.
      2. **PII Masking / Unmasking** — Anonymise sensitive tokens per-session.
      3. **Canary Token Management** — Inject and verify integrity beacons.

    Thread-safety: Concrete implementations MUST document their thread-safety
    guarantees. The session-scoped PII maps in particular require locking if
    the same session is accessed from multiple threads simultaneously.
    """

    # ── Input Inspection ─────────────────────────────────────────────────────

    @abstractmethod
    def inspect_input(self, prompt: str) -> Tuple[bool, float, str]:
        """
        Analyse a user-supplied prompt for adversarial content.

        Args:
            prompt: The raw user message text.

        Returns:
            A 3-tuple ``(is_safe, threat_score, reason)`` where:
              • ``is_safe``     — ``True`` if the prompt passes all checks.
              • ``threat_score``— Continuous score ∈ [0.0, 1.0].
              • ``reason``      — Human-readable justification string.

        Raises:
            Nothing — errors must be caught internally and reflected in the
            tuple.  This keeps the pipeline's control flow clean.
        """

    # ── PII Handling ─────────────────────────────────────────────────────────

    @abstractmethod
    def mask_pii(self, text: str, session_id: str) -> str:
        """
        Replace personally identifiable information with typed placeholders.

        The replacement mapping (``{ placeholder → original }``) is stored in
        an ephemeral per-session dict and is NOT persisted to disk.

        Args:
            text:       Input text that may contain PII.
            session_id: Session scope for the placeholder mapping.

        Returns:
            Text with all detected PII replaced by ``[TYPE_N]`` tokens.

        Raises:
            ``PIIProcessingException`` on unrecoverable errors.
        """

    @abstractmethod
    def unmask_pii(self, text: str, session_id: str) -> str:
        """
        Restore ``[TYPE_N]`` placeholders to their original values.

        Args:
            text:       Text containing PII placeholders.
            session_id: Session scope to look up the placeholder mapping.

        Returns:
            Text with all known placeholders restored to original values.
            Unknown placeholders are left as-is (do not raise).

        Raises:
            ``PIIProcessingException`` on unrecoverable errors.
        """

    # ── Canary Token Management ───────────────────────────────────────────────

    @abstractmethod
    def inject_canary(self, system_prompt: str) -> Tuple[str, str]:
        """
        Append a cryptographically unique canary token to a system prompt.

        The canary allows the pipeline to detect if the model is leaking its
        system instructions in user-visible output.

        Args:
            system_prompt: The original system / developer directive text.

        Returns:
            A 2-tuple ``(modified_prompt, canary_token)`` where:
              • ``modified_prompt`` — system prompt with the canary appended.
              • ``canary_token``    — the raw token string to verify against.
        """

    @abstractmethod
    def verify_canary(self, output_text: str, canary_token: str) -> bool:
        """
        Check whether the LLM's output contains the injected canary token.

        Args:
            output_text:  The raw text returned by the upstream LLM.
            canary_token: The token generated by a prior ``inject_canary`` call.

        Returns:
            ``True`` if the canary is present in the output (indicating
            system-prompt leakage); ``False`` otherwise.
        """

    # ── Convenience: Full report ──────────────────────────────────────────────

    def full_inspect(self, prompt: str) -> SecurityReport:
        """
        Thin wrapper that converts the raw tuple from ``inspect_input`` into a
        typed ``SecurityReport`` schema.  Concrete classes may override this
        to add richer category classification.
        """
        from core.schemas import ThreatCategory  # local import to avoid circularity

        is_safe, score, reason = self.inspect_input(prompt)
        if is_safe:
            category = ThreatCategory.CLEAN
        elif score >= 0.8:
            category = ThreatCategory.JAILBREAK_ATTEMPT
        else:
            category = ThreatCategory.PROMPT_INJECTION

        return SecurityReport(
            is_safe=is_safe,
            threat_score=score,
            category=category,
            reason=reason,
        )
