"""
modules/security/canary_guard.py
──────────────────────────────────
Dynamic cryptographic canary token generator and output auditor.

How it works:
  1. ``inject(system_prompt)`` — Generates a UUID4-based canary string and
     appends it invisibly to the system prompt.  The canary is NOT shown to
     the end user in normal operation.
  2. ``verify(output_text, canary_token)`` — Scans the LLM's raw output for
     the presence of the canary string.  If found, it means the model repeated
     a portion of its system prompt back to the user — a clear indicator of
     system-prompt leakage.

Token format (configurable via Settings):
  ``[[CANARY-<UUID4>]]``
  e.g. ``[[CANARY-3f2a1b4c-8d5e-4f67-a890-123456789abc]]``
"""

from __future__ import annotations

import logging
import re
import uuid
from typing import Optional, Tuple

from config.settings import get_settings

logger = logging.getLogger(__name__)


class CanaryGuard:
    """
    Canary token lifecycle manager for system-prompt leakage detection.

    Usage::

        guard = CanaryGuard()
        modified_prompt, token = guard.inject("You are a helpful assistant.")
        # … send modified_prompt to LLM …
        leaked = guard.verify(llm_output, token)
        if leaked:
            raise CanaryLeakageException(token, session_id=session_id)
    """

    def __init__(self, pattern: Optional[str] = None) -> None:
        """
        Args:
            pattern: Format string containing ``{token}`` placeholder.
                     Defaults to the value in ``Settings.canary_pattern``.
        """
        settings = get_settings()
        self._pattern = pattern or settings.canary_pattern

        if "{token}" not in self._pattern:
            raise ValueError(
                "CanaryGuard pattern must contain the '{token}' placeholder. "
                f"Got: {self._pattern!r}"
            )

        # Pre-build a regex that matches any canary generated by this guard.
        # The UUID portion is captured in group 1 for precise extraction.
        escaped = re.escape(self._pattern).replace(r"\{token\}", r"([0-9a-f\-]{36})")
        self._canary_regex = re.compile(escaped, re.IGNORECASE)

    # ── Public API ────────────────────────────────────────────────────────────

    def inject(self, system_prompt: str) -> Tuple[str, str]:
        """
        Append a unique canary token to a system prompt.

        The canary is appended on a new line after the main body so that it
        does not interrupt the semantic flow of the system instructions.

        Args:
            system_prompt: Original system / developer directive text.

        Returns:
            ``(modified_prompt, canary_token)`` where ``canary_token`` is the
            raw UUID string (without the surrounding delimiters) needed for
            verification.
        """
        raw_token = str(uuid.uuid4())
        formatted = self._pattern.format(token=raw_token)
        separator = "\n" if system_prompt.strip() else ""
        modified = f"{system_prompt}{separator}{formatted}"

        logger.debug("Canary injected — token=%s", raw_token)
        return modified, raw_token

    def verify(self, output_text: str, canary_token: str) -> bool:
        """
        Check whether ``output_text`` contains the given canary token.

        Both the formatted canary string (``[[CANARY-<uuid>]]``) and the raw
        UUID itself are checked, making detection robust against partial
        leakage or delimiter stripping by the model.

        Args:
            output_text:  Raw LLM response text to audit.
            canary_token: UUID string returned by a prior ``inject`` call.

        Returns:
            ``True`` if leakage is detected; ``False`` otherwise.
        """
        if not output_text or not canary_token:
            return False

        # Check 1: Full formatted canary present in output
        formatted_canary = self._pattern.format(token=canary_token)
        if formatted_canary in output_text:
            logger.warning(
                "CANARY LEAKAGE — full canary token '%s' found in LLM output.",
                formatted_canary,
            )
            return True

        # Check 2: Raw UUID present (model may have stripped delimiters)
        if canary_token in output_text:
            logger.warning(
                "CANARY LEAKAGE — raw UUID '%s' found in LLM output.",
                canary_token,
            )
            return True

        # Check 3: Regex match for any structurally valid canary in output
        for match in self._canary_regex.finditer(output_text):
            found_uuid = match.group(1)
            if found_uuid == canary_token:
                logger.warning(
                    "CANARY LEAKAGE — regex match for canary UUID '%s' in output.",
                    canary_token,
                )
                return True

        logger.debug("Canary verification passed — no leakage detected.")
        return False

    def extract_canaries(self, text: str) -> list[str]:
        """
        Extract all canary UUIDs found in arbitrary text.

        Useful for forensic audit logging.

        Args:
            text: Text to scan.

        Returns:
            List of UUID strings (may be empty).
        """
        return [m.group(1) for m in self._canary_regex.finditer(text)]
